Repository skyrim-multiplayer/skymp, pull requests merged in 2021-08, with the labels that each got.

#112 feat(skymp5-server): use messaging protocol version as SLikeNet password
  docs/SUMMARY.md
  docs/docs_maintainer_rules.md
  skymp5-server/cpp/mp_common/Config.h
  skymp5-server/cpp/mp_common/Networking.cpp
  skymp5-server/cpp/mp_common/Networking.h
Labels: status:review

#119 internal: downgrade required CMake version
  CMakeLists.txt
  README.md
  chakra-wrapper/CMakeLists.txt
  client-deps/CMakeLists.txt
  skymp5-client/CMakeLists.txt
  skymp5-front/CMakeLists.txt
  skymp5-functions-lib/CMakeLists.txt
  skymp5-scripts/CMakeLists.txt
  skymp5-server/CMakeLists.txt
  skymp5-server/cmake-js-fetch/CMakeLists.txt
  skyrim-platform/CMakeLists.txt
  skyrim-platform/src/platform_se/CMakeLists.txt
Labels: status:review

#116 Remove -fpermissive compiler option
  CMakeLists.txt
Labels: status:review

#110 feat(skymp5-server): don't rewrite esp/esm files in RAM
  skymp5-server/cpp/lib_espm/Combiner.cpp
  skymp5-server/cpp/lib_espm/Combiner.h
  skymp5-server/cpp/lib_espm/GroupUtils.h
  skymp5-server/cpp/lib_espm/espm.cpp
  skymp5-server/cpp/lib_espm/espm.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.cpp
  skymp5-server/cpp/unit/EspmTest.h
Labels: status:review

#125 internal: fix chakra-wrapper linking on Linux
  CMakeLists.txt
  chakra-wrapper/CMakeLists.txt
  skymp5-server/cpp/CMakeLists.txt
  skyrim-platform/src/platform_se/CMakeLists.txt
Labels: status:review

#123 feat(skymp5-server)!: add json extension to files created by FileDatabase
  skymp5-server/cpp/server_guest_lib/FileDatabase.cpp
Labels: status:testing

#134 internal: support coverage reports on Windows
  .github/workflows/pr-windows.yml
  CMakeLists.txt
  README.md
  cmake/run_cppcoverage.cmake
  cmake/run_test_unit.cmake
  cmake/skymp_execute_process.cmake
  skymp5-server/cpp/CMakeLists.txt
Labels: status:review

#131 internal: install Chromium Embedded Framework via vcpkg
  overlay_ports/cef-prebuilt/CMakeLists.txt
  overlay_ports/cef-prebuilt/portfile.cmake
  overlay_ports/cef-prebuilt/vcpkg.json
  skyrim-platform/CMakeLists.txt
  skyrim-platform/src/platform_se/CMakeLists.txt
  vcpkg.json
Labels: status:review

#136 tests: stop checking scamp_native.ilk in distribution
  skymp5-server/cpp/unit/DistContentsExpected.json
  skymp5-server/cpp/unit/DistContentsTest.h
Labels: status:review

#137 internal(skymp5-server): delete unused papyrus_vm_main directory
  skymp5-server/cpp/papyrus_vm_main/main.cpp
  skymp5-server/cpp/papyrus_vm_main/tests.h
Labels: status:review

#121 feat(skymp5-server): memory-map esp/esm files
  skymp5-server/cpp/lib_espm/AllocatedBuffer.cpp
  skymp5-server/cpp/lib_espm/AllocatedBuffer.h
  skymp5-server/cpp/lib_espm/IBuffer.h
  skymp5-server/cpp/lib_espm/Loader.cpp
  skymp5-server/cpp/lib_espm/Loader.h
  skymp5-server/cpp/lib_espm/MappedBuffer.cpp
  skymp5-server/cpp/lib_espm/MappedBuffer.h
  skymp5-server/cpp/lib_espm/espm.cpp
  skymp5-server/cpp/lib_espm/espm.h
Labels: status:wip

#141 perf(skymp5-server): optimize memory allocation in pex reader
  skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
  skymp5-server/cpp/papyrus_vm_lib/Reader.h
Labels: status:review
