Repository skyrim-multiplayer/skymp, pull requests merged in 2021-12, with the labels that each got.

#587 internal: add Ubuntu build CI check
  .github/workflows/pr-ubuntu-docker.yml
  unit/DistContentsExpected.json
Labels: area:ci

#592 feat(skyrim-platform): add struct for overlay texts
  client-deps/Data/Interface/Fonts/font.spritefont
  skyrim-platform/src/platform_se/skyrim_platform/TPOverlayService.cpp
  skyrim-platform/src/platform_se/skyrim_platform/TPOverlayService.h
  skyrim-platform/src/platform_se/skyrim_platform/main.cpp
  skyrim-platform/src/tilted/ui/DX11RenderHandler.cpp
  skyrim-platform/src/tilted/ui/DX11RenderHandler.h
  skyrim-platform/src/tilted/ui/MyRenderHandler.h
  skyrim-platform/src/tilted/ui/OverlayClient.cpp
  skyrim-platform/src/tilted/ui/OverlayClient.h
  skyrim-platform/src/tilted/ui/TextToDraw.h
  unit/DistContentsExpected.json
Labels: area:skyrim-platform, status:wip

#585 feat(skymp5-server): print unhandled messages
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/ActionListener.h
  skymp5-server/cpp/server_guest_lib/IActionListener.h
  skymp5-server/cpp/server_guest_lib/PacketParser.cpp
Labels: merge-to:indev

#620 feat(skymp5-server): add account of magic effects of armor
  docs/docs_onhit_and_damage.md
  skymp5-server/cpp/lib_espm/espm.cpp
  skymp5-server/cpp/lib_espm/espm.h
  skymp5-server/cpp/server_guest_lib/formulas/TES5DamageFormula.cpp
  unit/EspmTest.cpp
Labels: merge-to:indev

#648 feat: add missing Papyrus funcs
  skymp5-functions-lib/index.ts
  skymp5-server/cpp/server_guest_lib/PapyrusActor.h
Labels: merge-to:indev
