Repository skyrim-multiplayer/skymp, pull requests merged in 2021-07, with the labels that each got.

#49 add feature to choose default spawn points
  skymp5-server/ts/settings.ts
  skymp5-server/ts/systems/spawn.ts
Labels: status:wip

#47 Add target TSConverter
  skyrim-platform/src/platform_se/CMakeLists.txt
  skyrim-platform/src/platform_se/codegen/FunctionsDump.txt
  skyrim-platform/src/platform_se/codegen/TSConverter.cpp
  skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt
  skyrim-platform/src/platform_se/codegen/convert-files/FunctionsDump.txt
Labels: status:review

#54 Fix codegen in clean build
  skyrim-platform/src/platform_se/CMakeLists.txt
  skyrim-platform/src/platform_se/codegen/TSConverter.cpp
Labels: status:review

#52 Cleanup apply_default_settings.cmake
  cmake/apply_default_settings.cmake
Labels: status:wip

#59 Fix server startup
  docs/docs_running_a_server.md
  docs/docs_server_configuration_reference.md
  skymp5-client/CMakeLists.txt
  skymp5-scripts/CMakeLists.txt
  skymp5-server/CMakeLists.txt
  skymp5-server/cpp/CMakeLists.txt
  skymp5-server/cpp/addon/main.cc
  skymp5-server/cpp/lib_espm/Loader.h
  skymp5-server/ts/CMakeLists.txt
  skymp5-server/ts/manifestGen.ts
Labels: status:review

#66 Fix typos in SkyrimPlatform docs
  docs/docs_skyrim_platform.md
Labels: status:review

#61 Update docs_repository.md
  docs/docs_repository.md
Labels: status:review

#67 Update README.md
  README.md
Labels: status:review

#65 Fix npm working directory
  cmake/npm.cmake
  skymp5-server/CMakeLists.txt
  skymp5-server/ts/CMakeLists.txt
  skyrim-platform/CMakeLists.txt
  skyrim-platform/src/platform_se/CMakeLists.txt
Labels: status:wip

#79 Change SkyrimMultiplayer to SkyMP in readme
  README.md
Labels: status:review

#81 Allow passing backslashes to SKYRIM_DIR
  CMakeLists.txt
  skyrim-platform/CMakeLists.txt
Labels: status:testing

#73 Document supported generator on Windows
  docs/docs_cmake_workflow.md
Labels: status:review

#86 Fix Discord links
  README.md
  docs/README.md
Labels: status:review

#72 Improve code readability
  skymp5-server/cpp/server_guest_lib/IDatabase.h
Labels: status:review

#92 docs: fix highlighting in running server docs
  docs/docs_database_drivers.md
  docs/docs_running_a_server.md
  docs/docs_server_configuration_reference.md
Labels: status:review

#91 internal: profile cmake code in CI
  .github/workflows/cmake.yml
Labels: status:wip

#99 tests(skymp5-server): unit tests for iterating GRUP children in lib_espm
  skymp5-server/cpp/lib_espm/Combiner.h
  skymp5-server/cpp/lib_espm/espm.cpp
  skymp5-server/cpp/lib_espm/espm.h
  skymp5-server/cpp/unit/EspmTest.h
Labels: status:testing

#69 Document client installation
  docs/SUMMARY.md
  docs/docs_client_installation.md
Labels: status:review

#89 fix(skymp5-server): correctly handle IO error in FileDatabase upsert
  skymp5-server/cpp/server_guest_lib/FileDatabase.cpp
Labels: status:review

#105 docs: describe Skyrim files needed for running tests
  README.md
  skymp5-server/cpp/unit/EspmTest.h
Labels: status:review

#101 tests: verify that all distribution files present
  skymp5-server/CMakeLists.txt
  skymp5-server/cpp/CMakeLists.txt
  skymp5-server/cpp/unit/DistContentsExpected.json
  skymp5-server/cpp/unit/DistContentsTest.h
  skymp5-server/cpp/unit/main.cpp
  skyrim-platform/tools/dev_service/index.js
Labels: status:review
