Repository skyrim-multiplayer/skymp, pull requests merged in 2022-12, with the labels that each got.

#1186 perf: improve game framerate
  skymp5-client/src/extensions/objectReferenceEx.ts
  skymp5-client/src/messages.ts
  skymp5-client/src/modelSource/remoteServer.ts
  skymp5-client/src/view/formView.ts
  skymp5-client/src/view/modelApplyUtils.ts
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/MpObjectReference.h
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
Labels: merge-to:indev

#1193 refact: make codestyle more consistent
  skymp5-client/src/skympClient.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-server/cpp/lib_espm/espm.cpp
Labels: merge-to:indev

#1227 internal: update chakracore to 2022-11-09
  .github/workflows/deploy.yml
  .github/workflows/pr-ubuntu-docker.yml
  overlay_ports/chakracore/fix-debug-linux-build.patch
  overlay_ports/chakracore/portfile.cmake
  overlay_ports/chakracore/vcpkg.json
Labels: merge-to:indev

#1243 internal: run yarn-audit-fix for some ts code
  skymp5-front/yarn.lock
  skymp5-server/yarn.lock
Labels: merge-to:indev

#1272 feat(skymp5-functions-lib): implement timed rewards
  skymp5-functions-lib/index.ts
  skymp5-functions-lib/src/logic/PlayerController.ts
  skymp5-functions-lib/src/logic/SweetTaffyTimedRewards.test.ts
  skymp5-functions-lib/src/logic/SweetTaffyTimedRewards.ts
  skymp5-functions-lib/src/logic/TestUtils.ts
  skymp5-functions-lib/src/mpApiInteractor.ts
Labels: merge-to:indev

#1245 feat: refactor chat protocol & implement new features
  skymp5-front/src/constructorComponents/chat/index.js
  skymp5-front/src/constructorComponents/chat/input/styles.scss
  skymp5-front/src/constructorComponents/chat/styles.scss
  skymp5-front/src/features/login/LoginForm.js
  skymp5-functions-lib/src/logic/Command.ts
  skymp5-functions-lib/src/logic/GameModeListener.ts
  skymp5-functions-lib/src/logic/PlayerController.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-functions-lib/src/logic/TestUtils.ts
  skymp5-functions-lib/src/mpApiInteractor.ts
  skymp5-functions-lib/src/props/chatProperty.ts
  skymp5-functions-lib/src/types/settings.ts
  skymp5-functions-lib/src/utils/parseChatMessage.test.ts
  skymp5-functions-lib/src/utils/parseChatMessage.ts
Labels: merge-to:indev

#1212 feat(skymp5-server): implement animation system and actor values setting
  skymp5-server/cpp/addon/main.cc
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/ActionListener.h
  skymp5-server/cpp/server_guest_lib/ActorValues.h
  skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp
  skymp5-server/cpp/server_guest_lib/AnimationSystem.h
  skymp5-server/cpp/server_guest_lib/CropRegeneration.cpp
  skymp5-server/cpp/server_guest_lib/GetBaseActorValues.cpp
  skymp5-server/cpp/server_guest_lib/GetBaseActorValues.h
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/MpChangeForms.cpp
  skymp5-server/cpp/server_guest_lib/MpChangeForms.h
  skymp5-server/cpp/server_guest_lib/PacketParser.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.h
  unit/ActorTest.cpp
  unit/AnimationSystemTest.cpp
  unit/ChangeValuesTest.cpp
  unit/CropRegenerationTest.cpp
  unit/HealthRestorationTest.cpp
  unit/HitTest.cpp
  unit/PapyrusActorTest.cpp
  unit/RespawnTest.cpp
  unit/SaveStorageTest.cpp
  unit/TES5DamageFormulaTest.cpp
Labels: area:server

#1281 refact(skymp5-server): move some properties to pImpl
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
Labels: area:server, merge-to:indev

#1268 feat(skymp5-server): implement Papyrus Actor methods GetActorValue and IsEquipped
  skymp5-server/cpp/server_guest_lib/Inventory.cpp
  skymp5-server/cpp/server_guest_lib/Inventory.h
  skymp5-server/cpp/server_guest_lib/PapyrusActor.cpp
  skymp5-server/cpp/server_guest_lib/PapyrusActor.h
Labels: merge-to:indev
