Repository skyrim-multiplayer/skymp, pull requests merged in 2022-07, with the labels that each got.

#1154 feat(skymp5-client): add hotkey to toggle nicknames visiblity and change some others
  skymp5-client/src/features/browser.ts
  skymp5-client/src/view/formView.ts
Labels: area:client

#1159 feat(skymp5-server): added more edible items
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/PieScript.cpp
  skymp5-server/cpp/server_guest_lib/PieScript.h
Labels: area:server, merge-to:indev

#1167 internal: install sprintf-js as an npm dependency
  skymp5-functions-lib/package.json
  skymp5-functions-lib/src/lib/sprintf-js/index.d.ts
  skymp5-functions-lib/src/lib/sprintf-js/index.js
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-functions-lib/yarn.lock
Labels: merge-to:indev

#1173 internal: fix invalid gamemode build via bundling required modules
  skymp5-functions-lib/package.json
Labels: merge-to:indev

#621 feat(skymp5-server): set log level from config
  skymp5-server/cpp/addon/main.cc
Labels: merge-to:indev

#1185 feat(skymp5-client): temporary disable combat timitng
  skymp5-client/src/index.ts
  skymp5-client/src/sweetpie/playerCombatSystem.ts
Labels: merge-to:indev

#1172 feat(skymp5-functions-lib): introduce chat radius
  docs/docs_server_configuration_reference.md
  skymp5-functions-lib/src/mpApiInteractor.ts
  skymp5-functions-lib/src/types/settings.ts
Labels: merge-to:indev

#1166 feat(skymp5-front): make chat list resizable & focus input after click
  skymp5-front/package.json
  skymp5-front/src/constructorComponents/chat/dices/index.tsx
  skymp5-front/src/constructorComponents/chat/index.js
  skymp5-front/src/constructorComponents/chat/styles.scss
  skymp5-front/yarn.lock
Labels: merge-to:indev

#1187 feat(skymp5-scripts): add door locking scripts
  skymp5-scripts/pex/SweetGateLocker.pex
  skymp5-scripts/pex/SweetGateLockerCheck.pex
  skymp5-scripts/psc/SweetGateLocker.psc
  skymp5-scripts/psc/SweetGateLockerCheck.psc
  unit/DistContentsExpected.json
Labels: merge-to:indev

#1143 feat(skymp5-server): add some craft-related logs
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1180 feat(skymp5-server): lower log level for saved changeforms
  skymp5-server/cpp/server_guest_lib/AsyncSaveStorage.cpp
Labels: merge-to:indev

#1169 fix(skymp5-server): add a pointer safety check
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
Labels: merge-to:indev

#1191 feat(skymp5-functions-lib): don't teleport non-dm players on leave
  skymp5-functions-lib/src/logic/SweetPieRound.test.ts
  skymp5-functions-lib/src/logic/SweetPieRound.ts
Labels: merge-to:indev
