Repository skyrim-multiplayer/skymp, pull requests merged in 2022-02, with the labels that each got.

#891 feat(skymp5-functions-lib): reset spawnpoint on player disconnect
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-functions-lib/src/logic/SweetPieRound.test.ts
  skymp5-functions-lib/src/logic/SweetPieRound.ts
Labels: merge-to:indev

#902 feat: SweetPie game mode logic update
  skymp5-functions-lib/index.ts
  skymp5-functions-lib/src/logic/GameModeListener.ts
  skymp5-functions-lib/src/logic/PlayerController.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-functions-lib/src/logic/SweetPieMap.ts
  skymp5-functions-lib/src/logic/SweetPieRound.ts
  skymp5-functions-lib/src/logic/TestUtils.ts
  skymp5-functions-lib/src/mpApiInteractor.ts
  skymp5-functions-lib/src/types/mp.d.ts
  skymp5-server/cpp/addon/main.cc
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
Labels: merge-to:indev

#900 internal: update default spawn point
  skymp5-functions-lib/index.ts
  skymp5-server/CMakeLists.txt
Labels: merge-to:indev

#907 feat(skymp5-functions-lib): add more cities
  skymp5-functions-lib/index.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
  skymp5-functions-lib/src/logic/SweetPieMap.ts
  skymp5-functions-lib/src/logic/SweetPieRound.test.ts
  skymp5-functions-lib/src/logic/SweetPieRound.ts
Labels: merge-to:indev

#911 feat(skymp5-client): added simple network information system
  skymp5-client/CMakeLists.txt
  skymp5-client/src/index.ts
  skymp5-client/src/netInfoSystem.ts
  skymp5-client/src/remoteServer.ts
  skymp5-client/src/skympClient.ts
Labels: area:client

#905 feat(skymp5-server): add notifications and other pie script improvements
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/PieScript.cpp
  skymp5-server/cpp/server_guest_lib/PieScript.h
Labels: merge-to:indev

#936 feat(skymp5-server): don't allow downloading of esm/esp files
  skymp5-server/ts/ui.ts
Labels: merge-to:indev

#921 feat(skymp5-functions-lib): placeholder function for papyrus
  skymp5-functions-lib/index.ts
Labels: merge-to:indev

#932 fix(skymp5-scripts): Updated SweetDamage to be more stable
  skymp5-scripts/psc/SweetDamage.psc
Labels: merge-to:indev

#939 fix: address chat escaping issues
  skymp5-front/src/constructorComponents/chat/index.js
  skymp5-front/src/features/chat/index.js
  skymp5-front/src/features/chat/styles.scss
  skymp5-functions-lib/src/mpApiInteractor.ts
  skymp5-functions-lib/src/props/chatProperty.ts
Labels: merge-to:indev

#906 fix(skymp5-server): disable Pospelov and Xccane console priviligies
  skymp5-server/cpp/server_guest_lib/ConsoleCommands.cpp
  unit/ConsoleCommandTest.cpp
Labels: merge-to:indev

#950 feat(skymp5-client): update nicknames visibility
  skymp5-client/src/view.ts
Labels: area:client

#947 feat(skymp5-client): improve combat system
  skymp5-client/src/index.ts
  skymp5-client/src/playerCombatSystem.ts
  skymp5-client/src/utils.ts
Labels: area:client

#989 feat: bump client-server protocol version
  skymp5-server/cpp/mp_common/Config.h
Labels: merge-to:sweetpie

#1000 feat(skymp5-functions-lib): increase win reward
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.test.ts
  skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
Labels: merge-to:sweetpie

#1002 fix(skymp5-client): fix remote ref id and local ref id mismatch in some cases
  skymp5-client/src/remoteServer.ts
  skymp5-client/src/view.ts
Labels: area:client
