Repository skyrim-multiplayer/skymp, pull requests merged in 2023-04, with the labels that each got.

#1294 feat(skymp5-server): implement an imitation of bound weapons
  skymp5-server/cpp/lib_espm/espm.h
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.cpp
  skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.h
  skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp
  skymp5-server/cpp/server_guest_lib/SweetPieScript.h
Labels: area:server, merge-to:indev

#1370 feat(skymp5-server): play weapon drawing animation when a player equips a bound one
  skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp
Labels: area:server

#1379 feat(skymp5-server): improve mp-api events error handling
  skymp5-server/cpp/addon/ScampServerListener.cpp
Labels: merge-to:indev

#1381 fix(skymp5-server): fix always throwing mp.lookupEspmRecord API
  skymp5-server/cpp/addon/ScampServer.cpp
Labels: merge-to:indev

#1384 fix(skymp5-server): fix server crash related to TS-to-Papyrus functions registration
  skymp5-server/cpp/addon/ScampServer.cpp
Labels: merge-to:indev

#1368 feat: support multiline messages & fix chat parser a bit
  skymp5-front/src/constructorComponents/chat/index.js
  skymp5-front/src/constructorComponents/chat/input/index.tsx
  skymp5-front/src/constructorComponents/chat/styles.scss
  skymp5-front/src/utils/replaceIfMoreThan20.js
  skymp5-functions-lib/src/utils/parseChatMessage.test.ts
  skymp5-functions-lib/src/utils/parseChatMessage.ts
Labels: merge-to:indev
