Repository skyrim-multiplayer/skymp, pull requests merged in 2023-06, with the labels that each got.

#1431 internal: fix gamemode build
  skymp5-functions-lib/src/logic/listeners/harvestingSystem/index.ts
Labels: merge-to:indev

#1430 feat(skymp5-server): implement skill-based damage multipliers
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/lib_espm/espm.cpp
  skymp5-server/cpp/lib_espm/espm.h
  skymp5-server/cpp/server_guest_lib/PartOne.h
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieDamageFormula.cpp
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieDamageFormula.h
Labels: merge-to:indev

#1433 fix(skymp5-functions-lib): fix dices
  skymp5-functions-lib/index.ts
  skymp5-functions-lib/src/logic/listeners/commands/rollCommand.ts
Labels: merge-to:indev

#1437 feat(skymp5-functions-lib): implement skill menu rebalance
  skymp5-front/src/features/skillsMenu/content.ts
  skymp5-front/src/features/skillsMenu/index.tsx
  skymp5-functions-lib/src/logic/listeners/commands/skillCommand.ts
  skymp5-functions-lib/src/logic/listeners/commands/skillDiceCommand.ts
  skymp5-functions-lib/src/logic/listeners/harvestingSystem/index.ts
Labels: merge-to:indev

#1462 feat(skymp5-server): decrease stamina on dual attack
  skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp
Labels: area:server, merge-to:indev

#1456 fix(skymp5-server): fix ObjectReference property values
  libespm/include/libespm/espm.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/ScriptVariablesHolder.cpp
  skymp5-server/cpp/server_guest_lib/ScriptVariablesHolder.h
  unit/VirtualMachineTest.cpp
Labels: merge-to:indev

#1447 feat(skymp5-functions-lib): add /tp command
  skymp5-functions-lib/index.ts
  skymp5-functions-lib/src/logic/listeners/commands/tpCommand.ts
Labels: merge-to:indev

#1472 fix(skymp5-server): rename GetActorValue to GetActorValuePercentage
  skymp5-server/cpp/server_guest_lib/PapyrusActor.cpp
  skymp5-server/cpp/server_guest_lib/PapyrusActor.h
Labels: merge-to:indev

#1479 feat: revert "finally enable gamemode after saves load & save teleport points"
  skymp5-functions-lib/src/logic/listeners/commands/tpCommand.ts
  skymp5-functions-lib/src/logic/listeners/sweetpie/SweetPieGameModeListener.ts
  skymp5-functions-lib/src/mpApiInteractor.ts
  skymp5-functions-lib/src/utils/persistentStorage.ts
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/addon/main.cc
  skymp5-server/cpp/server_guest_lib/AsyncSaveStorage.cpp
  skymp5-server/cpp/server_guest_lib/AsyncSaveStorage.h
  skymp5-server/cpp/server_guest_lib/FileDatabase.cpp
  skymp5-server/cpp/server_guest_lib/FileDatabase.h
  skymp5-server/cpp/server_guest_lib/IDatabase.h
  skymp5-server/cpp/server_guest_lib/ISaveStorage.h
  skymp5-server/cpp/server_guest_lib/MigrationDatabase.cpp
  skymp5-server/cpp/server_guest_lib/MigrationDatabase.h
  skymp5-server/cpp/server_guest_lib/MongoDatabase.cpp
  skymp5-server/cpp/server_guest_lib/MongoDatabase.h
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/MpForm.cpp
  skymp5-server/cpp/server_guest_lib/MpForm.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/MpObjectReference.h
  skymp5-server/cpp/server_guest_lib/PapyrusObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.h
  unit/ActorTest.cpp
  unit/ActorsMapTest.cpp
  unit/HeuristicPolicyTest.cpp
  unit/ObjectReferenceTest.cpp
  unit/PapyrusCompatibilityTest.cpp
  unit/PapyrusDebugTest.cpp
  unit/PapyrusObjectReferenceTest.cpp
  unit/PartOne_ActivateTest.cpp
  unit/PickUpItemCountTest.cpp
  unit/SaveStorageTest.cpp
  unit/WorldStateTest.cpp
Labels: merge-to:indev

#1477 feat(skymp5-server): support IsBlocking animation variable in Papyrus
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/ActionListener.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/PacketParser.cpp
  unit/PapyrusObjectReferenceTest.cpp
Labels: merge-to:indev

#1465 fix(skymp5-server): remove block from players when unblock animation has not been sent
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/PacketParser.cpp
Labels: area:server

#1489 fix(skymp5-server): fix crafted item not adding
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpObjectReference.h
Labels: merge-to:indev

#1476 fix(skymp5-functions-lib): add lvlist support to harvester module
  skymp5-functions-lib/src/logic/PlayerController.ts
  skymp5-functions-lib/src/logic/listeners/commands/skillCommand.ts
  skymp5-functions-lib/src/logic/listeners/commands/skillDiceCommand.ts
  skymp5-functions-lib/src/logic/listeners/harvestingSystem/index.ts
  skymp5-functions-lib/src/mpApiInteractor.ts
Labels: merge-to:indev
