Repository skyrim-multiplayer/skymp, pull requests merged in 2023-08, with the labels that each got.

#1647 fix(skymp5-server): set ActorValues from the game files
  skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp
  skymp5-server/cpp/server_guest_lib/CropRegeneration.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
Labels: area:server, merge-to:indev

#1654 feat(skymp5-server): expose system addresses to javascript
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/addon/ScampServer.h
  skymp5-server/cpp/mp_common/Networking.cpp
  skymp5-server/cpp/mp_common/NetworkingCombined.h
  skymp5-server/cpp/mp_common/NetworkingInterface.h
  skymp5-server/cpp/mp_common/NetworkingMock.cpp
  skymp5-server/cpp/mp_common/NetworkingMock.h
  skymp5-server/ts/scampNative.ts
  skymp5-server/ts/systems/login.ts
Labels: merge-to:indev

#1655 feat(skymp5-server): add more info to discord logs channel & fix unexpected actors exchange
  skymp5-server/ts/settings.ts
  skymp5-server/ts/systems/login.ts
Labels: merge-to:indev

#1656 fix(skymp5-server): fix offline mode not working due to Discord stuff
  skymp5-server/ts/systems/discordBanSystem.ts
Labels: merge-to:indev

#1624 fix(skymp5-server): hotfix timers
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.h
Labels: merge-to:sweetpie

#1662 fix(skymp5-server): implement bulk inventory updates
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/FormCallbacks.h
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.h
  skymp5-server/cpp/server_guest_lib/ServerState.h
  unit/ConsoleCommandTest.cpp
  unit/DropItemTest.cpp
  unit/PartOne_ActivateTest.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1671 feat(skymp5-server): add weapon type dependent stamina consumption
  docs/docs_server_configuration_reference.md
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/AnimationSystem.cpp
  skymp5-server/cpp/server_guest_lib/AnimationSystem.h
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.h
  skymp5-server/cpp/server_guest_lib/WorldState.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.h
  unit/AnimationSystemTest.cpp
  unit/WorldStateTest.cpp
Labels: area:server, merge-to:indev

#1670 feat(skymp5-server): add more conjured weapons
  skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.cpp
  skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.h
  skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp
  skymp5-server/cpp/server_guest_lib/SweetPieScript.h
Labels: area:server, merge-to:indev
