Repository skyrim-multiplayer/skymp, pull requests merged in 2024-02, with the labels that each got.

#1709 feat: enable/disable game forms
  skymp5-client/src/services/services/remoteServer.ts
  skymp5-client/src/view/modelApplyUtils.ts
  skymp5-server/cpp/addon/property_bindings/IsDisabledBinding.cpp
  skymp5-server/cpp/server_guest_lib/MpForm.cpp
  skymp5-server/cpp/server_guest_lib/MpForm.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
Labels: area:server, merge-to:indev

#1838 feat(skymp5-server): support death item
  libespm/include/libespm/NPC_.h
  libespm/src/NPC_.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
Labels: merge-to:indev

#1842 fix(skymp5-server): fix ObjectReference.Disable/Enable Papyrus natives
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
Labels: merge-to:indev

#1845 fix(skymp5-server): forbid permanent restoration for 5 sec
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
Labels: area:server, merge-to:indev

#1846 fix(skymp5-server): correct damage formula for unarmed attacks
  skymp5-server/cpp/server_guest_lib/formulas/TES5DamageFormula.cpp
Labels: area:server, merge-to:indev

#1848 feat(skymp5-server): add conditional inventory cleanup on respawn
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/WorldState.cpp
  skymp5-server/cpp/server_guest_lib/WorldState.h
Labels: merge-to:indev

#1849 feat: remove ammo on shots
  skymp5-client/src/index.ts
  skymp5-client/src/messages.ts
  skymp5-client/src/services/messages/anyMessage.ts
  skymp5-client/src/services/messages/playerBowShotMessage.ts
  skymp5-client/src/services/services/playerBowShotService.ts
  skymp5-server/cpp/messages/MsgType.h
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/ActionListener.h
  skymp5-server/cpp/server_guest_lib/PacketParser.cpp
Labels: merge-to:indev

#1768 fix(skymp5-server): file database saving fix
  skymp5-server/cpp/server_guest_lib/database_drivers/FileDatabase.cpp
Labels: area:server

#1853 fix(skymp5-server): change cooldown host in OnHit event
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
Labels: area:server, merge-to:indev

#1856 fix(skymp5-server): prevent fast host switch
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
Labels: merge-to:indev

#1855 fix(skymp5-server): fix GetRaceId not respecting templates & load order
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  unit/PartOne_ActivateTest.cpp
Labels: merge-to:indev

#1861 fix(papyrus-vm): fix prop get/set opcodes
  papyrus-vm/src/papyrus-vm-lib/ActivePexInstance.cpp
Labels: merge-to:indev

#1862 feat(skymp5-server): add damage mult to server config
  docs/docs_server_configuration_reference.md
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/server_guest_lib/formulas/DamageMultFormula.cpp
  skymp5-server/cpp/server_guest_lib/formulas/DamageMultFormula.h
Labels: area:server, merge-to:indev
