Repository skyrim-multiplayer/skymp, pull requests merged in 2024-12, with the labels that each got.

#2233 feat(skymp5-server): add OnFireBlocked to ReadBookEvent for blocked book reading handling
  skymp5-server/cpp/server_guest_lib/gamemode_events/ReadBookEvent.cpp
  skymp5-server/cpp/server_guest_lib/gamemode_events/ReadBookEvent.h
Labels: merge-to:indev

#2236 feat(skymp5-server): add spell retrieval methods to MpActor and PapyrusActor
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.h
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.h
Labels: merge-to:indev

#2258 fix(skymp5-server): add missing variable to a log
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
Labels: merge-to:indev

#2240 feat: use simdjson in some FromJson calls
  serialization/include/archives/SimdJsonInputArchive.h
  skymp5-server/cpp/messages/MessageBase.h
  skymp5-server/cpp/messages/MessageSerializerFactory.cpp
  skymp5-server/cpp/messages/MessageSerializerFactory.h
  skymp5-server/cpp/server_guest_lib/Equipment.cpp
  skymp5-server/cpp/server_guest_lib/Inventory.cpp
  skymp5-server/cpp/server_guest_lib/Inventory.h
  unit/ArchiveTest.cpp
  unit/MovementSerializationTest.cpp
Labels: merge-to:indev, merge-to:sweetpie

#2256 feat(skymp5-server): add Quest.GetStage stub & disable some bad scripts
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusClassesFactory.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusQuest.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusQuest.h
Labels: merge-to:indev, merge-to:sweetpie

#2261 feat(skymp5-server): add onUpdateAppearanceAttempt gamemode event
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/Appearance.h
  skymp5-server/cpp/server_guest_lib/gamemode_events/UpdateAppearanceAttemptEvent.cpp
  skymp5-server/cpp/server_guest_lib/gamemode_events/UpdateAppearanceAttemptEvent.h
Labels: merge-to:indev

#2265 perf(skymp5-server): avoid copying in DynamicFields.set (mp.set)
  skymp5-server/cpp/server_guest_lib/DynamicFields.cpp
  skymp5-server/cpp/server_guest_lib/DynamicFields.h
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/MpObjectReference.h
  skymp5-server/cpp/server_guest_lib/gamemode_events/RespawnEvent.cpp
Labels: merge-to:indev

#1852 fix(skymp5-server): correct stamina regeneration formula
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
Labels: area:server, merge-to:indev, merge-to:sweetpie

#2247 feat: add SweetPieSpellDamageFormula for spell damage modification
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieDamageFormula.h
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieSpellDamageFormula.cpp
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieSpellDamageFormula.h
Labels: merge-to:indev, merge-to:sweetpie
