Repository skyrim-multiplayer/skymp, pull requests merged in 2024-01, with the labels that each got.

#1794 fix(skymp5-server): fix server crash in SweetPieScript
  skymp5-server/cpp/server_guest_lib/SweetPieScript.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1795 fix(skymp5-server): fix bad COBJ override
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/FindRecipe.cpp
  unit/CraftTest.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1796 fix(skymp5-server): fix crash in ObjectReference.MoveTo
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1797 feat(skymp5-server): mp.set now live-updates appearance
  skymp5-client/src/services/messages/updateAppearanceMessage.ts
  skymp5-client/src/services/services/remoteServer.ts
  skymp5-client/src/view/formView.ts
  skymp5-server/cpp/addon/property_bindings/AppearanceBinding.cpp
Labels: merge-to:indev

#1792 fix(skymp5-server): fix Papyrus AddItem/RemoveItem functions
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusActor.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1798 feat(skymp5-server): add Form.GetName Papyrus native (stub)
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusForm.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusForm.h
Labels: merge-to:indev

#1808 feat(skymp5-server): restrict SweetCantDrop server-side
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
Labels: merge-to:indev

#1799 fix(skymp5-server): fix ObjectReference.AddItem corner cases
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
Labels: merge-to:indev

#1814 fix(skymp5-server): fix outfit generation
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  unit/PartOne_ActivateTest.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1806 feat(skymp5-server): add damage mult
  skymp5-server/cpp/addon/ScampServer.cpp
  skymp5-server/cpp/server_guest_lib/formulas/DamageMultFormula.cpp
  skymp5-server/cpp/server_guest_lib/formulas/DamageMultFormula.h
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieDamageFormula.cpp
  skymp5-server/cpp/server_guest_lib/formulas/SweetPieDamageFormula.h
Labels: merge-to:indev, merge-to:sweetpie

#1742 fix(skymp5-server): remove restore functionality from CropRegeneration
  skymp5-server/cpp/server_guest_lib/CropRegeneration.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1816 fix(skymp5-server): decrease unarmed damage if the hit was blocked
  skymp5-server/cpp/server_guest_lib/formulas/TES5DamageFormula.cpp
Labels: area:server

#1819 feat(skymp5-server): add logs in crop regeneration
  skymp5-server/cpp/server_guest_lib/CropRegeneration.cpp
Labels: area:server

#1815 fix(skymp5-server): fix segfault in GetEditorLocationalData
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
Labels: merge-to:indev, merge-to:sweetpie

#1812 fix(skymp5-server): use aggressor position instead of view vector in block necessity condition
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
Labels: area:server, merge-to:indev

#1833 fix: isDead property not being included in createActor message
  skymp5-client/src/services/messages/createActorMessage.ts
  skymp5-client/src/services/services/remoteServer.ts
  skymp5-client/src/view/formView.ts
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
Labels: merge-to:indev

#1817 fix(skymp5-server): fix potential Discord rate limit
  skymp5-server/ts/systems/login.ts
Labels: merge-to:indev

#1837 fix(skymp5-server): fix keywords-related segfault in drop item
  skymp5-server/cpp/server_guest_lib/ActionListener.cpp
Labels: merge-to:indev

#1836 fix(skymp5-server): fix multiple Potemas dungeon issues & more
  skymp5-server/cpp/server_guest_lib/MpActor.cpp
  skymp5-server/cpp/server_guest_lib/PartOne.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusGame.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusGame.h
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.cpp
  skymp5-server/cpp/server_guest_lib/script_classes/PapyrusObjectReference.h
  skymp5-server/cpp/server_guest_lib/script_objects/MpFormGameObject.cpp
Labels: merge-to:indev
